version: '3.3'

services:
  nuxt:
    build:
      context: .
      dockerfile: /home/powerit/nuxt_little_test_project_compose/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./dist:/home/powerit/nuxt_little_test_project_compose/dist
    networks:
      - web

networks:
  web:
    external: true
