version: '3.3'

services:
  rust-mkdocs:
    image: docker.pkg.github.com/ULmadaDmitri/nuxt_little_test_project_registry/ui:dev
    ports: "82:82"
    container_name: nuxt_registry
    restart: unless-stopped
    networks:
      - web


networks:
  web:
    external: true
