version: '3.3'

services:
  nuxt:
    build:
      context: .
    ports:
      - "82:82"
    volumes:
      - ./dist:/home/powerit/nuxt_little_test_project_compose_registry/dist
    networks:
      - web

networks:
  web:
    external: true
