name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
         npx nuxt generate
         docker build -t nginx_driga /home/runner/work/nuxt_little_test_project/nuxt_little_test_project
         pwd
         ls -la
          
      - name: Add ssh key
        run: | 
          set -eu
          mkdir "$HOME/.ssh"
          ls -la
          echo "${{ secrets.SSH_KEY_CONNECTION }}" > $HOME/.ssh/key
          chmod 600 $HOME/.ssh/key
          pwd
      - name: Update host content   
        shell: bash
        env:
          USER: ${{ vars.user }}
          HOST: ${{ vars.host }}
          DIST: ${{ vars.dist }}
        run: |
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" -avz ./*  powerit@206.81.27.146:/home/powerit/nuxt_little_test_project
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no powerit@206.81.27.146 "docker run -d nginx_driga"
